### ISSUE TITLE
Peer review for Final Project

### ISSUE THREAD

**Issue by aravind1338** [mk-repos/Stats506_public#4]
Hi, I hope this feedback helps with your final draft!

1) Basic requirements: All the required sections are not present, you should add a method, results and conclusion section to the Rmd.

2) Introduction: You should add more detail to the intro, perhaps with more information of what you did to perform the analysis.

3) Data/Methods: The data source is mentioned, but you should add a link to the NHANES website where they can get the data. And you should also add a description of the methods used rather than just code. Maybe you can add some commenting to satisfy that requirement.

4) Results: This section is missing, but I assume you are still working on it.

5) Conclusion/Discussion: Should add this section.

Overall a very interesting project with a great question! Good luck!

**Comment by mk-repos** [comment]
Thank you for the review. Completed the report.
